title: Brane Framework
# email: your-email@example.com
description: >-
  Brane, a programmable application orchestration framework with a focus on privacy
baseurl: "/"
url: "https://braneframework.github.io"
github_username: BraneFramework

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  student_projects:
    output: true
    permalink: /:collection/:name
    layout: page

defaults:
  - scope:
      path: ""
      type: "student_projects"
    values:
      layout: "project"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
